### ISSUE TITLE
Input with OTU's as columns (not rows)

### ISSUE THREAD

**Issue by ptpell77** [tobiasgf/lulu#11]
I have a very large matrix 1.5 million OTU x 12,000 sample matrix that I would like to run LULU on. Unfortunately as output of dada2 the OTU are columns. This is of course easy to fix using dplyr commands, however they are intractable on a matrix this large. 

Is it possible to run LULU with OTU as columns? Thanks, Peter

**Comment by tobiasgf** [comment]
Hi Peter.
Not as it is now unfortunately.
Are you saying that that R cannot transpose ( t() ) a dataframe/matrix with those dimensions as yours ?
I would also expect that the LULU processing would take forever with that number of OTUs.
We are working on a much faster version of LULU, which would solve the speed issue.
But whether it would generally be preferable to have the OTUs as columns (in input and output) I cannot judge, would be more directly compatible with dada2 and vegan, etc...

Regards
Tobias

**Comment by ptpell77** [comment]
Thanks Tobias,
I will await the speedier solution before running LULU!
