### ISSUE TITLE
how to set OTU similarity using lulu parameters?

### ISSUE THREAD

**Issue by gabrielet** [tobiasgf/lulu#17]
As per my question, I don't understand how to obtain OTU with a specific similarity threshold. The tutorial you provided in the main page of this github repository states that it is:

> A step-by-step walk-through with the 97% clustered (VSEARCH) data from the LULU paper.

However, I see that in the walk-through you're using BLASTn for the matchlist (or I am missing the vsearch part) and then `lulu()` with some parameters. What is not clear, to me, is how you set the parameters to have 97% similarity between final OTUs. So, is there some references that may help understand how to set parameters in order to, say, get a 95%, 97%, or, for example 93.25% similarity between the final clustered OTUs?

**Comment by ewmorr** [comment]
Hi @gabrielet . Maybe you've figured this out by now, but I just came across your post as I was looking for something else. Here is what I used in the past
```
lulu(
otutable = asv_tab,
matchlist = asv_matches,
minimum_match = 84
)
```
Where `minimum_match` is the flag telling lulu the minimum sequence similarity for a match, and the argument to `matchlist` is a table of results from vsearch. The vsearch command as follows using a representative sequence fasta `ASVs.fa`as input (from dada2 ASVs in this case)
```
vsearch --usearch_global ASVs.fa --db ASVs.fa --self --id .84 --iddef 1 --userout match_list.0.84min.txt -userfields query+target+id --maxaccepts 0 --query_cov .9 --maxhits 10
```
Note that you could modify some of these parameters to meet your needs (e.g., `--query_cov`), but I think this was the recommended protocol from a lulu tutorial I was reading. The results from vsearch are read into R by
```
asv_matches = read.table("match_list.0.84min.txt", header=FALSE,as.is=TRUE, stringsAsFactors=FALSE) #note the flags here. algorithm does not work if these are not set (fails a couple of ways)
```
I had a note as you can see that the flags are needed for the lulu algorithm to work correctly, but I don't remember all the details. Following is a sample of the vsearch results so you can see what is needed as input. Column 1 is the seed, col 2 is the hit, and col 3 is the percent ID.
```
ASV_1	ASV_150	99.4
ASV_1	ASV_162	99.4
ASV_1	ASV_174	99.4
ASV_1	ASV_179	99.4
ASV_1	ASV_232	99.4
ASV_1	ASV_772	96.9
ASV_1	ASV_610	95.8
ASV_1	ASV_974	94.4
ASV_1	ASV_4	92.5
ASV_1	ASV_208	91.9
```

**Comment by gabrielet** [comment]
Hey @ewmorr, thank you for your reply! It's been quite a while since i posted that i almost forgot about LULU.
What you said made me think about a possible solution which relies on vsearch as a primary filter. What i am thinking about is the `--id` parameter in the vsearch command. I can actually set it to the minimum similarity threshold, e.g. 0.97, and vsearch should give me already what i need. then with LULU i get the clusters and i should be confident i get the minimum similarity i wanted, in the first place. I will need to try this out and see what happens. I will update this post, once i will be able to try what you said and what i thought.

In the meanwhile, [here is the solution](https://github.com/benjjneb/dada2/issues/947#issuecomment-586630401) i am actually using.

**Comment by adrientaudiere** [comment]
Hey @gabrielet and @ewmorr, 
You may be interested in the [MiscMetabar](https://adrientaudiere.github.io/MiscMetabar/) I'm currently developing. In particular, the `asv2otu` (two methods : using [DECIPHER::Clusterize()](https://rdrr.io/pkg/DECIPHER/man/Clusterize.html) or [vsearch](https://github.com/torognes/vsearch) sofltware) and `lulu_pq` functions may help.

**Comment by gabrielet** [comment]
@adrientaudiere thank you, i will surely have a look at your method :-)

**Comment by adrientaudiere** [comment]
Hi @gabrielet and @ewmorr,
There is a bug in lulu (see [issue 8](https://github.com/tobiasgf/lulu/issues/8)), so @frederic-mahe developed an alternative called [mumu](https://github.com/frederic-mahe/mumu). I also built a function in R to use mumu : [`mumu_pq()`](https://adrientaudiere.github.io/MiscMetabar/reference/mumu_pq.html).

**Comment by gabrielet** [comment]
@adrientaudiere thanks for the heads-up!

**Comment by gabrielet** [comment]
i think we can close the topic, since alternatives to lulu were found.
