### ISSUE TITLE
buildOTUtable_simple.sh missing from repo

### ISSUE THREAD

**Issue by Talitrus** [tobiasgf/lulu#3]
Hi Tobias,

I can't seem to find the script `buildOTUtable_simple.sh` in the provided CLI scripts. Am I missing something?

Best,
Bryan

**Comment by tobiasgf** [comment]
Hi.
Sorry.
For some reason I cannot push my updates to GitHub at the moment. So I post the lines of code here. Just put it in a text file named buildOTUtable_simple.sh

---

#!/bin/bash
FASTA=$1
SCRIPT="OTU_contingency_table_simple.py"
STATS="${FASTA/.fas/.stats}"
SWARMS="${FASTA/.fas/.swarms}"
REPRESENTATIVES="${FASTA/.fas/.centroids}"
UCHIME="${FASTA/.fas/.uchime}"
OTU_TABLE="${FASTA/.fas/.otutable}"

    "${SCRIPT}" \
    "${REPRESENTATIVES}" \
    "${STATS}" \
    "${SWARMS}" \
    "${UCHIME}" \
    S[0-9][0-9][0-9]*.fas > "${OTU_TABLE}"
